# Generated by Django 2.0 on 2018-06-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypart',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='trainday',
            name='timestamp',
        ),
    ]
