# Generated by Django 2.0 on 2018-06-18 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTrainingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('recommendations', models.TextField(blank=True, max_length=1000)),
                ('motivation_quotes', models.TextField(blank=True, max_length=1000)),
                ('day_of_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
                ('week_number', models.PositiveIntegerField(default=1)),
                ('exercises', models.ManyToManyField(to='exercise.ExerciseSet')),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingday',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='training_days',
        ),
        migrations.DeleteModel(
            name='TrainingDay',
        ),
        migrations.AddField(
            model_name='workouttrainingday',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise.Workout'),
        ),
    ]
