# Generated by Django 2.0 on 2018-06-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20180618_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='rest',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
