# Generated by Django 2.0 on 2018-06-18 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20180618_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouttrainingday',
            old_name='week_number',
            new_name='phase',
        ),
    ]
