# Generated by Django 2.0 on 2018-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20180618_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(max_length=1)),
                ('weeks_duration', models.PositiveIntegerField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='workouttrainingday',
            name='workout',
        ),
        migrations.AddField(
            model_name='workoutphase',
            name='training_days',
            field=models.ManyToManyField(to='exercise.WorkoutTrainingDay'),
        ),
        migrations.AddField(
            model_name='workout',
            name='phases',
            field=models.ManyToManyField(to='exercise.WorkoutPhase'),
        ),
    ]
