# Generated by Django 2.0 on 2018-06-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0007_auto_20180618_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutphase',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutphase',
            name='weeks_duration',
            field=models.PositiveIntegerField(),
        ),
    ]
