# Generated by Django 2.0 on 2018-06-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20180618_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttrainingday',
            name='phase',
        ),
    ]
