# Generated by Django 2.0 on 2018-06-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('instructions', models.TextField(blank=True, max_length=1000)),
                ('tips', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='gym/exercises/')),
                ('primary_muscles', models.ManyToManyField(related_name='primary_muscles', to='body.Muscle')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_muscles', to='body.Muscle')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_sets', models.IntegerField(default=3)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(default=0)),
                ('reps_unit', models.CharField(choices=[('RE', 'Reps'), ('MI', 'Minutes'), ('SE', 'Seconds'), ('KM', 'kilometers'), ('UF', 'Until Failure')], default='RE', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_unit', models.CharField(choices=[('KG', 'Kg.'), ('BW', 'Body Weight'), ('KH', 'Kms per hour')], default='RE', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='sets',
            field=models.ManyToManyField(related_name='sets', to='gym.Set'),
        ),
    ]
