# Generated by Django 2.0 on 2018-06-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField(default=0)),
                ('reps_unit', models.CharField(choices=[('RE', 'Reps'), ('MI', 'Minutes'), ('SE', 'Seconds'), ('KM', 'kilometers'), ('UF', 'Until Failure')], default='RE', max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_unit', models.CharField(choices=[('KG', 'Kg.'), ('BW', 'Body Weight'), ('KH', 'Kms per hour')], default='RE', max_length=2)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Exercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='reps_unit',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='weight_unit',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='number_of_sets',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.Set'),
        ),
    ]
