# Generated by Django 2.0 on 2018-06-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20180619_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='sets',
            field=models.ManyToManyField(related_name='sets', to='gym.Set'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Exercise'),
        ),
    ]
