# Generated by Django 2.0 on 2018-06-20 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='planner/program/')),
                ('summary', models.TextField(blank=True, max_length=1500)),
                ('level', models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='IN', max_length=2)),
                ('goal', models.CharField(choices=[('BU', 'Bulking'), ('CU', 'Cutting'), ('MA', 'Maintaining')], default='MA', max_length=2)),
                ('start_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('weeks_duration', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='planner/workout/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], default='MO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('recommendations', models.TextField(blank=True, max_length=1000)),
                ('motivation_quotes', models.TextField(blank=True, max_length=1000)),
                ('exercises', models.ManyToManyField(to='gym.ExerciseSet')),
            ],
        ),
        migrations.AddField(
            model_name='workoutday',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.WorkoutSession'),
        ),
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.ManyToManyField(to='planner.WorkoutDay'),
        ),
        migrations.AddField(
            model_name='programphase',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.Workout'),
        ),
        migrations.AddField(
            model_name='program',
            name='phases',
            field=models.ManyToManyField(to='planner.ProgramPhase'),
        ),
    ]
