# Generated by Django 2.0 on 2018-06-20 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 23, 10, 14, 956302)),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 20, 23, 10, 14, 956279)),
        ),
    ]
